title: Senthil Nayagan
author:
  name: Senthil Nayagan
  email: hello@senthilnayagan.com
first_name: Senthil
middle_name:
last_name: Nayagan
email: hello@senthilnayagan.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog

url: https://senthilnayagan.github.io/
twitter_username: SenthilNayagan
github_username:  SenthilNayagan


# Build settings
theme: minima

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, how-to-do-things.txt]