# Site
name: Senthil Nayagan
title: Senthil Nayagan
description: "It’s my tech blog where I explore various data engineering concepts. I’m also making up stories about design and coding principles."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
disqus: "senthilnayagan"
include: ["_pages"]
permalink: /:title

# Authors
authors:
  senthil:
    name: "Senthil Nayagan"
    display_name: "Senthil Nayagan"
    gravatar: 6fc127cda8cd99830932538a58dc6173
    email: "hello@senthilnayagan.com"
    web: https://senthilnayagan.com/
    twitter: https://twitter.com/senthilnayagan
    description: "I am a Data Engineer by profession, a Rustacean by interest, and an avid Content Creator."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Exclude metadata and development time dependencies 
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, how-to-do-things.txt]