# Site
name: "Senthil Nayagan"
title: "Senthil Nayagan"
description: "It’s my tech blog where I explore various programming concepts. I’m also making up stories about design and coding principles."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo_solid_bg.png'
baseurl: ""
disqus: 'senthilnayagan'
mailchimp-list: 'https://gmail.us17.list-manage.com/subscribe?u=155954fdd35cc37fcbfab134a&id=acc42a78d4'
include: ["_pages"]
permalink: /:categories/:year/:title
email: hello@senthilnayagan.com

# Authors
authors:
  senthil:
    name: "Senthil Nayagan"
    display_name: "Senthil Nayagan"
    gravatar: 6fc127cda8cd99830932538a58dc6173
    email: "hello@senthilnayagan.com"
    web: https://senthilnayagan.com/
    twitter: https://twitter.com/SenthilNayagan
    description: "I am a Data Engineer by profession, a Rustacean by interest, and an avid Content Creator at present."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]