name: Senthil Nayagan
title: Senthil Nayagan
author:
  name: Senthil Nayagan
  email: hello@senthilnayagan.com
description: "Technical blog covers Data Engineering and Design Principles."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: "/" # the subpath of your site, e.g. /blog
include: ["_pages"]

#url: https://senthilnayagan.github.io/
#twitter_username: SenthilNayagan
#github_username:  SenthilNayagan


# Build settings
theme: minima

markdown: kramdown

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Define defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, how-to-do-things.txt]